# NumPy UltraQuick Tutorial

[Numpy](https://numpy.org/doc/stable/index.html) is a Python library for creating and manipulating matrices, the main data structure used by ML algorithms. [Matrices](https://en.wikipedia.org/wiki/Matrix_(mathematics)) are mathematical objects used to store values in rows and columns.

Python calls matrices *lists*, NumPy calls them *arrays* and TensorFlow calls them *tensors*. Python represents matrices with the [list data type](https://docs.python.org/3/library/stdtypes.html#lists).

This Colab is not an exhaustive tutorial on NumPy.  Rather, this Colab teaches you just enough to use NumPy in the Colab exercises of Machine Learning Crash Course.

## Import NumPy module

Run the following code cell to import the NumPy module:

In [2]:
import numpy as np

## Populate arrays with specific numbers

Call `np.array` to create a NumPy array with your own hand-picked values. For example, the following call to `np.array` creates an 8-element array:

In [3]:
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


You can also use `np.array` to create a two-dimensional array. To create a two-dimensional array specify an extra layer of square brackets. For example, the following call creates a 3x2 array:

In [4]:
two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


To populate an array with all zeroes, call `np.zeros`. To populate an array with all ones, call `np.ones`.

## Populate arrays with sequences of numbers

You can populate an array with a sequence of numbers:

In [5]:
sequence_of_integers = np.arange(5, 12)
print(sequence_of_integers)

[ 5  6  7  8  9 10 11]


Notice that `np.arange` generates a sequence that includes the lower bound (5) but not the upper bound (12).

## Populate arrays with random numbers

NumPy provides various functions to populate arrays with random numbers across certain ranges. For example, `np.random.randint` generates random integers between a low and high value. The following call populates a 6-element array with random integers between 50 and 100.




In [6]:
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6))
print(random_integers_between_50_and_100)

[79 82 69 54 62 74]


Note that the highest generated integer `np.random.randint` is one less than the `high` argument.

To create random floating-point values between 0.0 and 1.0, call `np.random.random`. For example:

In [7]:
random_floats_between_0_and_1 = np.random.random([6])
print(random_floats_between_0_and_1)

[0.15498687 0.27518245 0.78862611 0.19081638 0.48908926 0.92225156]


## Mathematical Operations on NumPy Operands

If you want to add or subtract two arrays, linear algebra requires that the two operands have the same dimensions. Furthermore, if you want to multiply two arrays, linear algebra imposes strict rules on the dimensional compatibility of operands. Fortunately, NumPy uses a trick called [**broadcasting**](https://developers.google.com/machine-learning/glossary/#broadcasting) to virtually expand the smaller operand to dimensions compatible for linear algebra. For example, the following operation uses broadcasting to add 2.0 to the value of every item in the array created in the previous code cell:

In [8]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

[2.15498687 2.27518245 2.78862611 2.19081638 2.48908926 2.92225156]


The following operation also relies on broadcasting to multiply each cell in an array by 3:

In [9]:
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300)

[237 246 207 162 186 222]


## Task 1: Create a Linear Dataset

Your goal is to create a simple dataset consisting of a single feature and a label as follows:

1. Assign a sequence of integers from 6 to 20 (inclusive) to a NumPy array named `feature`.
2. Assign 15 values to a NumPy array named `label` such that:

```
   label = (3)(feature) + 4
```
For example, the first value for `label` should be:

```
  label = (3)(6) + 4 = 22
 ```

In [14]:
import numpy as np

# 1. Assign a sequence of integers from 6 to 20 to a NumPy array named feature.
feature = np.arange(6, 21)

# 2. Assign values to a NumPy array named label using the formula.
label = 3 * feature + 4

print("Feature:", feature)
print("Label:", label)


Feature: [ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Label: [22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


## Task 2: Add Some Noise to the Dataset

To make your dataset a little more realistic, insert a little random noise into each element of the `label` array you already created. To be more precise, modify each value assigned to `label` by adding a *different* random floating-point value between -2 and +2.

Don't rely on broadcasting. Instead, create a `noise` array having the same dimension as `label`.

In [18]:
import numpy as np

# Assuming label is an existing numpy array
label = np.array([5, 10, 15, 20, 25])  # Example label array

# Create a noise array with the same shape as label
noise = np.random.uniform(-2, 2, label.shape)

# Add the noise to the label
label = label.astype(float)  # Convert label to float
label += noise


print(noise)  # This will print the random noise values
print(label)  # This will print the label values after adding the noise


[-0.89222672  1.80369558 -0.09772822  1.77533707 -1.55066304]
[ 4.10777328 11.80369558 14.90227178 21.77533707 23.44933696]


In [19]:
# Another possible solution to Task 2.

noise = (np.random.random([15]) * 4) - 2
print(noise)
label = label + noise
print(label)

[-0.97913121 -0.22382614 -1.32224301  0.75332535 -0.35081182  0.10865017
  1.44200828 -0.3885456   0.65109345 -1.546429    0.84271428  1.70205778
  1.10657341 -1.78866751 -1.15072132]


ValueError: operands could not be broadcast together with shapes (5,) (15,) 